apiVersion: apps/v1
kind: Deployment
metadata:
  name: control
spec:
  selector:
    matchLabels:
      app: control
      version: v1
  replicas: {{ .Values.replicas}}
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
        sidecar.istio.io/inject: 'true'
      labels:
        app: control
        version: v1
    spec:
      containers:
        - name: control
          image: quay.io/kiali/demo_travels_control:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          securityContext:
            privileged: false
          env:
            - name: PORTAL_SERVICES
              value: "voyages.fr;http://voyages.travel-portal:8000,viaggi.it;http://viaggi.travel-portal:8000,travels.uk;http://travels.travel-portal:8000"

